<?php

/**
 * @file
 * Provides a json migrate entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function json_migrate_theme() {
  return [
    'json_migrate' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for json migrate templates.
 *
 * Default template: json-migrate.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the json migrate information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_json_migrate(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
